[package]
name = "brainy_application"
version = "0.1.0"
edition = "2024"

[build-dependencies]
prost-build = "0.14.3"

[dependencies]
# TODO: rexport them from domain
async-trait = "0.1.89"
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
log = "0.4.29"
chrono = { version = "0.4.44", features = ["serde"] }
tokio = { version = "1.51.0", features = ["full"] }
serde_json = "1.0.149"
lol_html = "2.7.2"
base64 = "0.22.1"
prost = "0.14.3"
prost-types = "0.14.3"
# TODO: find something to do with this, move it to infrastructure
rig-core = { version = "0.35.0", features = ["pdf", "derive"] }
text-splitter = "0.30.1"
rig-sqlite = "0.2.4"
schemars = "1.2.1"
tokio-rusqlite = "0.6.0"
tokio-stream = "0.1.18"
async-stream = "0.3.6"
markdown = "1.0.0"

brainy_domain = { path = "../brainy_domain" }
injector = { path = "../injector" }
injector_derive = { path = "../injector_derive" }

[dev-dependencies]
mockall = "0.14.0"
