[package]
name = "brainy_infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "tls-native-tls", "macros", "sqlite", "chrono", "uuid" ] }
thiserror = "2.0.18"
tokio = { version = "1.51.0", features = ["full"] }
uuid = { version = "1.23.1", features = [ "v4", "serde" ] }
log = "0.4.29"
sqlite-vec = "0.1.9"
tokio-rusqlite = "0.6.0"

injector = { path = "../injector" }
injector_derive = { path = "../injector_derive" }

brainy_domain = { path = "../brainy_domain" }
brainy_application = { path = "../brainy_application" }
